#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod agent;
mod app;
mod cli;
mod curl_export;
mod curl_import;
mod engine;
mod history;
mod http;
mod icons;
mod json_view;
mod mcp;
mod model;
mod query;
mod redact;
mod secrets;
mod request;
#[cfg(test)]
mod test_server;
mod theme;
mod vars;

use app::{ApiTesterApp, OpenTabs, Settings};
use eframe::egui;
use model::PersistedState;
use std::io::Write;

/// Release builds are `panic = "abort"` with no console, so a crash would
/// otherwise vanish without a trace. Append it to a log the user can send.
fn install_crash_log() {
    let path = history::app_data_dir().join("crash.log");
    std::panic::set_hook(Box::new(move |info| {
        if let Some(dir) = path.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        let now = time::OffsetDateTime::now_utc()
            .format(&time::format_description::well_known::Rfc3339)
            .unwrap_or_default();
        let entry = format!("[{now}] v{}\n{info}\n\n", env!("CARGO_PKG_VERSION"));
        if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(&path) {
            let _ = f.write_all(entry.as_bytes());
        }
    }));
}

/// The plunger, as the window and taskbar icon. Raw 128x128 RGBA generated by
/// `packaging/icons/make-icons.ps1`; without it eframe shows its default "e".
fn window_icon() -> egui::IconData {
    egui::IconData {
        rgba: include_bytes!("../packaging/icons/window-128.rgba").to_vec(),
        width: 128,
        height: 128,
    }
}

fn main() -> eframe::Result<()> {
    install_crash_log();

    // `plunger <command>` runs headless (CLI or MCP server); no arguments opens the window.
    let args: Vec<String> = std::env::args().skip(1).collect();
    if !args.is_empty() {
        // The MCP server talks over the pipes its client gave it; never attach a console to it.
        if args[0] != "mcp" {
            cli::attach_parent_console();
        }
        std::process::exit(cli::run(args));
    }

    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([980.0, 680.0])
            .with_min_inner_size([620.0, 420.0])
            // Fixed id so eframe's state file lives in %APPDATA%\Plunger\data next to
            // the history database, instead of a folder named after the versioned title.
            .with_app_id("Plunger")
            .with_icon(window_icon()),
        // With the data-dir override, keep the window/tab state next to the
        // rest of the app data too.
        persistence_path: std::env::var_os(history::DATA_DIR_ENV)
            .filter(|d| !d.is_empty())
            .map(|_| history::app_data_dir().join("app.ron")),
        ..Default::default()
    };
    eframe::run_native(
        &format!("Plunger {}", env!("CARGO_PKG_VERSION")),
        options,
        Box::new(|cc| {
            fn load<T: serde::de::DeserializeOwned + Default>(storage: Option<&dyn eframe::Storage>, key: &str) -> T {
                storage.and_then(|s| eframe::get_value(s, key)).unwrap_or_default()
            }
            let settings: Settings = load(cc.storage, app::SETTINGS_KEY);
            theme::apply_theme(&cc.egui_ctx, settings.theme);

            let state: PersistedState = load(cc.storage, eframe::APP_KEY);
            let tabs: OpenTabs = load(cc.storage, app::TABS_KEY);
            Ok(Box::new(ApiTesterApp::from_persisted(state, tabs, settings)))
        }),
    )
}
